export const incident_lookup = {
  'door problem': 'DOOR_PROBLEM',
  'door malfunction': 'DOOR_PROBLEM',
  EMS: 'EMS',
  NYPD: 'NYPD',
  'medical assistance': 'EMS',
  'sick passenger': 'PASSENGER_ASSISTANCE',
  'assist an injured customer': 'PASSENGER_ASSISTANCE',
  'emergency teams': 'EMS',
  'brakes activated': 'BRAKES_ACTIVATED',
  disruptive: 'DISRUPTIVE',
  'switch work': 'SWITCH_MAINTENANCE',
  'track maintenance': 'TRACK_MAINTENANCE',
  'emergency brake cord': 'BRAKES_ACTIVATED',
  FDNY: 'FDNY',
  'track fire': 'TRACK_FIRE',
  flooding: 'FLOODING',
  'water from the tracks': 'FLOODING',
  'water on the tracks': 'FLOODING',
  'water condition': 'FLOODING',
  'remove a tree': 'REMOVED_DEBRIS',
  'removed a tree': 'REMOVED_DEBRIS',
  'remove tree': 'REMOVED_DEBRIS',
  'removed tree': 'REMOVED_DEBRIS',
  'debris on the track': 'REMOVED_DEBRIS',
  vandalized: 'VANDALISM',
  assaulted: 'ASSAULT',
  cleaning: 'CLEANING',
  'cleared water': 'FLOODING',
  'clear water': 'FLOODING',
  'clean a train': 'CLEANING',
  'needed to be cleaned': 'CLEANING',
  'broken rail': 'BROKEN_RAIL',
  'brakes to activate': 'BRAKES_ACTIVATED',
  'unauthorized person': 'UNAUTHORIZED_PERSON',
  'mechanical problem': 'MECHANICAL_PROBLEM',
  'mechanical issue': 'MECHANICAL_PROBLEM',
  'signal malfunction': 'SIGNAL_PROBLEM',
  'signal problem': 'SIGNAL_PROBLEM',
  'medical help': 'EMS',
  'medical attention': 'EMS',
  'switch problem': 'SWITCH_PROBLEM',
  'switch malfunction': 'SWITCH_PROBLEM',
  'brakes were activated': 'BRAKES_ACTIVATED',
  'brake was activated': 'BRAKES_ACTIVATED',
  "activated a train's brakes": 'BRAKES_ACTIVATED',
  'switch maintenance': 'SWITCH_MAINTENANCE',
  'network communication problem': 'NETWORK_PROBLEM',
  'network communications problem': 'NETWORK_PROBLEM',
  'removed a shopping cart': 'REMOVED_DEBRIS',
  'remove debris': 'REMOVED_DEBRIS',
  'removed debris': 'REMOVED_DEBRIS',
  'remove hanging debris': 'REMOVED_DEBRIS',
  'removed hanging debris': 'REMOVED_DEBRIS',
  'remove a walker': 'REMOVED_DEBRIS',
  'removed a walker': 'REMOVED_DEBRIS',
  'moved debris': 'REMOVED_DEBRIS',
  'move debris': 'REMOVED_DEBRIS',
  'brake cord': 'BRAKES_ACTIVATED',
  'track work': 'TRACK_MAINTENANCE',
  'electrical improvements': 'TRACK_MAINTENANCE',
  'struck by a train': 'PERSON_STRUCK',
  'marine traffic': 'MARINE_TRAFFIC',
  'boats to pass': 'MARINE_TRAFFIC',
  'maritime traffic': 'MARINE_TRAFFIC',
  'planned work': 'PLANNED_WORK',
  'slower speeds': 'SLOWER_SPEEDS',
  'signal modernization': 'SIGNAL_MAINTENANCE',
  'signal maintenance': 'SIGNAL_MAINTENANCE',
  'third-rail power': 'THIRD_RAIL_POWER',
  'third rail power': 'THIRD_RAIL_POWER',
  'loss of power': 'THIRD_RAIL_POWER',
  'loss of third rail power': 'THIRD_RAIL_POWER',
  'restored power': 'THIRD_RAIL_POWER',
  'wait longer': 'LONGER_WAIT',
  'longer wait': 'LONGER_WAIT',
  'running express': 'RUNNING_EXPRESS',
  'running on the express': 'RUNNING_EXPRESS',
  'run express': 'RUNNING_EXPRESS',
  'trains express': 'RUNNING_EXPRESS',
  'buses are detoured': 'BUS_DETOUR',
  'car in need of repairs': 'TRAIN_REPAIR',
  'car in need fo repair': 'TRAIN_REPAIR',
  'car that needs to be repaired': 'TRAIN_REPAIR',
  'train that needs to be repaired': 'TRAIN_REPAIR',
  'unable to move a train': 'TRAIN_REPAIR',
  'slow speeds': 'SLOWER_SPEEDS',
  'work equipment': 'WORK_EQUIPMENT',
  'work train': 'WORK_EQUIPMENT',
  'move equipment': 'WORK_EQUIPMENT',
  'moved equipment': 'WORK_EQUIPMENT',
  'refuse train': 'WORK_EQUIPMENT',
  'refuse collection train': 'WORK_EQUIPMENT',
  'move a crane': 'WORK_EQUIPMENT',
  'moved a crane': 'WORK_EQUIPMENT',
  'replace rails': 'RAIL_REPLACEMENT',
  'replaced rails': 'RAIL_REPLACEMENT',
  'replace a rail': 'RAIL_REPLACEMENT',
  'replaced a rail': 'RAIL_REPLACEMENT',
  'rail repairs': 'RAIL_REPLACEMENT',
  'repaired a rail': 'RAIL_REPLACEMENT',
  'completed replacing rails': 'RAIL_REPLACEMENT',
  'track replacement': 'RAIL_REPLACEMENT',
  'track inspection': 'TRACK_INSPECTION',
  'track inspection train': 'WORK_EQUIPMENT',
  'inspect tracks': 'TRACK_INSPECTION',
  'inspected tracks': 'TRACK_INSPECTION',
  'replace tracks': 'RAIL_REPLACEMENT',
  'repairing a damaged rail': 'RAIL_REPLACEMENT',
  'replaced a damage rail': 'RAIL_REPLACEMENT',
  'will arrive on': 'STATION_CHANGE',
  'arriving on': 'STATION_CHANGE',
  'departing from': 'STATION_CHANGE',
  'ceiling leak': 'STATION_MAINTENANCE',
  'structural maintenance': 'STATION_MAINTENANCE',
  'platform gap fillers': 'STATION_MAINTENANCE',
  'platform maintenance': 'STATION_MAINTENANCE',
  'running on the local track': 'RUNNING_LOCAL',
  'make local stops': 'RUNNING_LOCAL',
  'running local': 'RUNNING_LOCAL',
  'making local stops': 'RUNNING_LOCAL',
  'train crews we have available': 'STAFF_SHORTAGE',
  'trains we have available': 'EQUIPMENT_SHORTAGE',
  'data outage': 'INFORMATION_OUTAGE',
  'not run': 'NO_TRIP',
  'not take place': 'NO_TRIP',
  'from service': 'REMOVED_FROM_SERVICE',
  'moved a train': 'REMOVED_FROM_SERVICE',
  'moved an out-of-service': 'REMOVED_FROM_SERVICE',
  'network communication issue': 'NETWORK_PROBLEM',
  'network communications issue': 'NETWORK_PROBLEM',
  'network communication maintenance': 'NETWORK_MAINTENANCE',
  'share tracks': 'TRACK_SHARING',
  'share the tracks': 'TRACK_SHARING',
  'shared tracks': 'TRACK_SHARING',
  investigation: 'INVESTIGATION',
  investigate: 'INVESTIGATION',
  'train arrival information': 'INFORMATION_OUTAGE',
  'arrival times are currently unavailable': 'INFORMATION_OUTAGE',
  'someone in need': 'PASSENGER_ASSISTANCE',
  'person in need': 'PASSENGER_ASSISTANCE',
  'individual on the tracks': 'UNAUTHORIZED_PERSON',
  'individuals on the tracks': 'UNAUTHORIZED_PERSON',
  'fell on the tracks': 'UNAUTHORIZED_PERSON',
  suspended: 'SERVICE_SUSPENDED',
  'limited service': 'LIMITED_SERVICE',
  skipping: 'LIMITED_SERVICE',
  skips: 'LIMITED_SERVICE',
  'resumed stopping': 'REGULAR_SERVICE',
  'no northbound': 'LIMITED_SERVICE',
  // delay: 'DELAY',
  // delays: 'DELAY',
  smoke: 'SMOKE',
  'service in either direction': 'LIMITED_SERVICE',
  'resumed making regular station stops': 'REGULAR_SERVICE',
  derail: 'DERAILMENT',
}
