package io.github.mwdonohue.api.components.incidenttypes;

import java.util.HashMap;
import java.util.Map;

// Move to DB level, sucks here
public class IncidentTypes {
    public static final Map<String, String> lookup = new HashMap<>();
    static {
        lookup.put("door problem", "DOOR_PROBLEM");
        lookup.put("door malfunction", "DOOR_PROBLEM");
        lookup.put("EMS", "EMS");
        lookup.put("NYPD", "NYPD");
        lookup.put("medical assistance", "EMS");
        lookup.put("sick passenger", "PASSENGER_ASSISTANCE");
        lookup.put("assist an injured customer", "PASSENGER_ASSISTANCE");
        lookup.put("emergency teams", "EMS");
        lookup.put("brakes activated", "BRAKES_ACTIVATED");
        lookup.put("disruptive", "DISRUPTIVE");
        lookup.put("switch work", "SWITCH_MAINTENANCE");
        lookup.put("track maintenance", "TRACK_MAINTENANCE");
        lookup.put("emergency brake cord", "BRAKES_ACTIVATED");
        lookup.put("FDNY", "FDNY");
        lookup.put("track fire", "TRACK_FIRE");
        lookup.put("flooding", "FLOODING");
        lookup.put("water from the tracks", "FLOODING");
        lookup.put("water on the tracks", "FLOODING");
        lookup.put("water condition", "FLOODING");
        lookup.put("remove a tree", "REMOVED_DEBRIS");
        lookup.put("removed a tree", "REMOVED_DEBRIS");
        lookup.put("remove tree", "REMOVED_DEBRIS");
        lookup.put("removed tree", "REMOVED_DEBRIS");
        lookup.put("debris on the track", "REMOVED_DEBRIS");
        lookup.put("vandalized", "VANDALISM");
        lookup.put("assaulted", "ASSAULT");
        lookup.put("cleaning", "CLEANING");
        lookup.put("cleared water", "FLOODING");
        lookup.put("clear water", "FLOODING");
        lookup.put("clean a train", "CLEANING");
        lookup.put("needed to be cleaned", "CLEANING");
        lookup.put("broken rail", "BROKEN_RAIL");
        lookup.put("brakes to activate", "BRAKES_ACTIVATED");
        lookup.put("unauthorized person", "UNAUTHORIZED_PERSON");
        lookup.put("mechanical problem", "MECHANICAL_PROBLEM");
        lookup.put("mechanical issue", "MECHANICAL_PROBLEM");
        lookup.put("signal malfunction", "SIGNAL_PROBLEM");
        lookup.put("signal problem", "SIGNAL_PROBLEM");
        lookup.put("medical help", "EMS");
        lookup.put("medical attention", "EMS");
        lookup.put("switch problem", "SWITCH_PROBLEM");
        lookup.put("switch malfunction", "SWITCH_PROBLEM");
        lookup.put("brakes were activated", "BRAKES_ACTIVATED");
        lookup.put("brake was activated", "BRAKES_ACTIVATED");
        lookup.put("activated a train's brakes", "BRAKES_ACTIVATED");
        lookup.put("switch maintenance", "SWITCH_MAINTENANCE");
        lookup.put("network communication problem", "NETWORK_PROBLEM");
        lookup.put("network communications problem", "NETWORK_PROBLEM");
        lookup.put("removed a shopping cart", "REMOVED_DEBRIS");
        lookup.put("remove debris", "REMOVED_DEBRIS");
        lookup.put("removed debris", "REMOVED_DEBRIS");
        lookup.put("remove hanging debris", "REMOVED_DEBRIS");
        lookup.put("removed hanging debris", "REMOVED_DEBRIS");
        lookup.put("remove a walker", "REMOVED_DEBRIS");
        lookup.put("removed a walker", "REMOVED_DEBRIS");
        lookup.put("moved debris", "REMOVED_DEBRIS");
        lookup.put("move debris", "REMOVED_DEBRIS");
        lookup.put("brake cord", "BRAKES_ACTIVATED");
        lookup.put("track work", "TRACK_MAINTENANCE");
        lookup.put("electrical improvements", "TRACK_MAINTENANCE");
        lookup.put("struck by a train", "PERSON_STRUCK");
        lookup.put("marine traffic", "MARINE_TRAFFIC");
        lookup.put("boats to pass", "MARINE_TRAFFIC");
        lookup.put("maritime traffic", "MARINE_TRAFFIC");
        lookup.put("planned work", "PLANNED_WORK");
        lookup.put("slower speeds", "SLOWER_SPEEDS");
        lookup.put("signal modernization", "SIGNAL_MAINTENANCE");
        lookup.put("signal maintenance", "SIGNAL_MAINTENANCE");
        lookup.put("third-rail power", "THIRD_RAIL_POWER");
        lookup.put("third rail power", "THIRD_RAIL_POWER");
        lookup.put("loss of power", "THIRD_RAIL_POWER");
        lookup.put("loss of third rail power", "THIRD_RAIL_POWER");
        lookup.put("restored power", "THIRD_RAIL_POWER");
        lookup.put("wait longer", "LONGER_WAIT");
        lookup.put("longer wait", "LONGER_WAIT");
        lookup.put("running express", "RUNNING_EXPRESS");
        lookup.put("running on the express", "RUNNING_EXPRESS");
        lookup.put("run express", "RUNNING_EXPRESS");
        lookup.put("trains express", "RUNNING_EXPRESS");
        lookup.put("buses are detoured", "BUS_DETOUR");
        lookup.put("car in need of repairs", "TRAIN_REPAIR");
        lookup.put("car in need fo repair", "TRAIN_REPAIR");
        lookup.put("car that needs to be repaired", "TRAIN_REPAIR");
        lookup.put("train that needs to be repaired", "TRAIN_REPAIR");
        lookup.put("unable to move a train", "TRAIN_REPAIR");
        lookup.put("slow speeds", "SLOWER_SPEEDS");
        lookup.put("work equipment", "WORK_EQUIPMENT");
        lookup.put("work train", "WORK_EQUIPMENT");
        lookup.put("move equipment", "WORK_EQUIPMENT");
        lookup.put("moved equipment", "WORK_EQUIPMENT");
        lookup.put("refuse train", "WORK_EQUIPMENT");
        lookup.put("refuse collection train", "WORK_EQUIPMENT");
        lookup.put("move a crane", "WORK_EQUIPMENT");
        lookup.put("moved a crane", "WORK_EQUIPMENT");
        lookup.put("replace rails", "RAIL_REPLACEMENT");
        lookup.put("replaced rails", "RAIL_REPLACEMENT");
        lookup.put("replace a rail", "RAIL_REPLACEMENT");
        lookup.put("replaced a rail", "RAIL_REPLACEMENT");
        lookup.put("rail repairs", "RAIL_REPLACEMENT");
        lookup.put("repaired a rail", "RAIL_REPLACEMENT");
        lookup.put("completed replacing rails", "RAIL_REPLACEMENT");
        lookup.put("track replacement", "RAIL_REPLACEMENT");
        lookup.put("track inspection", "TRACK_INSPECTION");
        lookup.put("track inspection train", "WORK_EQUIPMENT");
        lookup.put("inspect tracks", "TRACK_INSPECTION");
        lookup.put("inspected tracks", "TRACK_INSPECTION");
        lookup.put("replace tracks", "RAIL_REPLACEMENT");
        lookup.put("repairing a damaged rail", "RAIL_REPLACEMENT");
        lookup.put("replaced a damage rail", "RAIL_REPLACEMENT");
        lookup.put("will arrive on", "STATION_CHANGE");
        lookup.put("arriving on", "STATION_CHANGE");
        lookup.put("departing from", "STATION_CHANGE");
        lookup.put("ceiling leak", "STATION_MAINTENANCE");
        lookup.put("structural maintenance", "STATION_MAINTENANCE");
        lookup.put("platform gap fillers", "STATION_MAINTENANCE");
        lookup.put("platform maintenance", "STATION_MAINTENANCE");
        lookup.put("running on the local track", "RUNNING_LOCAL");
        lookup.put("make local stops", "RUNNING_LOCAL");
        lookup.put("running local", "RUNNING_LOCAL");
        lookup.put("making local stops", "RUNNING_LOCAL");
        lookup.put("train crews we have available", "STAFF_SHORTAGE");
        lookup.put("trains we have available", "EQUIPMENT_SHORTAGE");
        lookup.put("data outage", "INFORMATION_OUTAGE");
        lookup.put("not run", "NO_TRIP");
        lookup.put("not take place", "NO_TRIP");
        lookup.put("from service", "REMOVED_FROM_SERVICE");
        lookup.put("moved a train", "REMOVED_FROM_SERVICE");
        lookup.put("moved an out-of-service", "REMOVED_FROM_SERVICE");
        lookup.put("network communication issue", "NETWORK_PROBLEM");
        lookup.put("network communications issue", "NETWORK_PROBLEM");
        lookup.put("network communication maintenance", "NETWORK_MAINTENANCE");
        lookup.put("share tracks", "TRACK_SHARING");
        lookup.put("share the tracks", "TRACK_SHARING");
        lookup.put("shared tracks", "TRACK_SHARING");
        lookup.put("investigation", "INVESTIGATION");
        lookup.put("investigate", "INVESTIGATION");
        lookup.put("train arrival information", "INFORMATION_OUTAGE");
        lookup.put("arrival times are currently unavailable", "INFORMATION_OUTAGE");
        lookup.put("someone in need", "PASSENGER_ASSISTANCE");
        lookup.put("person in need", "PASSENGER_ASSISTANCE");
        lookup.put("individual on the tracks", "UNAUTHORIZED_PERSON");
        lookup.put("individuals on the tracks", "UNAUTHORIZED_PERSON");
        lookup.put("fell on the tracks", "UNAUTHORIZED_PERSON");
        lookup.put("suspended", "SERVICE_SUSPENDED");
        lookup.put("limited service", "LIMITED_SERVICE");
        lookup.put("skipping", "LIMITED_SERVICE");
        lookup.put("skips", "LIMITED_SERVICE");
        lookup.put("resumed stopping", "REGULAR_SERVICE");
        lookup.put("no northbound", "LIMITED_SERVICE");
        lookup.put("smoke", "SMOKE");
        lookup.put("service in either direction", "LIMITED_SERVICE");
        lookup.put("resumed making regular station stops", "REGULAR_SERVICE");
        lookup.put("derail", "DERAILMENT");
    }
}
