export const incident_lookup = {
  'door problem': 'DOOR_PROBLEM',
  EMS: 'EMS',
  NYPD: 'NYPD',
  'brakes activated': 'BRAKES_ACTIVATED',
  disruptive: 'DISRUPTIVE',
  'switch work': 'SWITCH_WORK',
  'track maintenance': 'TRACK_MAINTENANCE',
  'emergency brake cord': 'BRAKES_ACTIVATED',
  FDNY: 'FDNY',
  'track fire': 'TRACK_FIRE',
  flooding: 'FLOODING',
  vandalized: 'VANDALISM',
  assaulted: 'ASSAULT',
  cleaning: 'CLEANING',
  'broken rail': 'BROKEN_RAIL',
  'brakes to activate': 'BRAKES_ACTIVATED',
  'unauthorized person': 'UNAUTHORIZED_PERSON',
  'mechanical problem': 'MECHANICAL_PROBLEM',
  'signal malfunction': 'SIGNAL_PROBLEM',
  'signal problem': 'SIGNAL_PROBLEM',
  'medical help': 'EMS',
  'switch problem': 'SWITCH_PROBLEM',
  'switch malfunction': 'SWITCH_PROBLEM',
  'brakes were activated': 'BRAKES_ACTIVATED',
  'switch maintenance': 'SWITCH_MAINTENANCE',
  'network communication problem': 'NETWORK_PROBLEM',
  'remove debris': 'REMOVED_DEBRIS',
  'removed debris': 'REMOVED_DEBRIS',
  'brake cord': 'BRAKES_ACTIVATED',
  'track work': 'TRACK_MAINTENANCE',
  'struck by a train': 'PERSON_STRUCK',
  'marine traffic': 'MARINE_TRAFFIC',
  'boats to pass': 'MARINE_TRAFFIC',
  'planned work': 'PLANNED_WORK',
  'slower speeds': 'SLOWER_SPEEDS',
  'signal modernization': 'SIGNAL_MODERNIZATION',
  'third-rail power': 'THIRD_RAIL_POWER',
  'buses are detoured': 'BUS_DETOUR',
  work_equipment: 'WORK_EQUIPMENT',
  'replace rails': 'RAIL_REPLACEMENT',
  'replaced rails': 'RAIL_REPLACEMENT',
}
